version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio_storage
    restart: always
    ports:
      - "9000:9000" # MinIO S3 API Endpoint
      - "9001:9001" # MinIO Web Console Dashboard
    environment:
      MINIO_ROOT_USER: admin_tokoku
      MINIO_ROOT_PASSWORD: PasswordKuat123!
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
    driver: local
