// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function FetchProducts():Promise<Array<models.Product>>;

export function GenerateSlug(arg1:string):Promise<string>;

export function GenerateUUID():Promise<string>;

export function GetConfig():Promise<models.StoreConfig>;

export function SaveConfig(arg1:models.StoreConfig):Promise<void>;

export function SyncProduct(arg1:models.Product):Promise<models.SyncResult>;

export function TriggerRebuild():Promise<string>;
