// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchProducts() {
  return window['go']['main']['App']['FetchProducts']();
}

export function GenerateSlug(arg1) {
  return window['go']['main']['App']['GenerateSlug'](arg1);
}

export function GenerateUUID() {
  return window['go']['main']['App']['GenerateUUID']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SyncProduct(arg1) {
  return window['go']['main']['App']['SyncProduct'](arg1);
}

export function TriggerRebuild() {
  return window['go']['main']['App']['TriggerRebuild']();
}
